# Generated by Django 6.0.3 on 2026-04-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_withdrawrequest_delete_withdrawalrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='available_balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='hold_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
