# Generated by Django 6.0.3 on 2026-04-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_wallet_available_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='balance',
            new_name='available_balance',
        ),
    ]
